CREATE TABLE `coupon` (
  `id` bigint(19) unsigned NOT NULL,
  `uid` bigint(19) unsigned NOT NULL DEFAULT '0',
  `batch_no` varchar(40) NOT NULL DEFAULT '' COMMENT '优惠券批次',
  `status` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT '0未使用,1已使用,2已失效',
  `enable_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '优惠券启用时间',
  `effective_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '优惠券有效期',
  `title` varchar(40) NOT NULL DEFAULT '' COMMENT '优惠券标题',
  `amount` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '抵扣金额，单位分',
  `type` varchar(20) NOT NULL DEFAULT '' COMMENT '优惠券类型',
  `minimal_order_amount` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '最小订单金额，单位分',
  `available_product` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '可用产品范围（小机柜，大机柜，座充等）二进制表示',
  `available_time_stage` varchar(20) NOT NULL DEFAULT '' COMMENT '可用时间段,如0-12',
  `available_platform` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '可用平台',
  `code` varchar(48) NOT NULL DEFAULT '' COMMENT '兑换码',
  `use_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '使用时间',
  `order_number` bigint(16) unsigned NOT NULL DEFAULT '0' COMMENT '使用的订单',
  `description` varchar(255) NOT NULL DEFAULT '' COMMENT '描述',
  `source_platform` varchar(40) NOT NULL DEFAULT '' COMMENT '来源平台',
  `ext_info` varchar(255) NOT NULL DEFAULT '' COMMENT '预留扩展字段',
  `create_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
  `uuid` varchar(64) NOT NULL DEFAULT '' COMMENT '唯一标识',
  `allid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `gmt_modify` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`,`id`),
  KEY `idx_uid_enable_time_effective_time_status` (`uid`,`enable_time`,`effective_time`,`status`) USING BTREE,
  KEY `idx_batch_no` (`batch_no`) USING BTREE,
  KEY `idx_code` (`code`) USING BTREE,
  KEY `idx_effective_time` (`effective_time`) USING BTREE,
  KEY `idx_create_time` (`create_time`) USING BTREE,
  KEY `idx_allid` (`allid`),
  KEY `idx_gmt_modify` (`gmt_modify`)
) ENGINE=TokuDB DEFAULT CHARSET=utf8mb4 COMMENT='优惠券';